dist: trusty
sudo: required
language: cpp
compiler:
    gcc
before_install:
    - sudo apt-get -qq update
script:
    ./run.sh && cat /tmp/output

notifications:
    email:
        on_success: never
        on_failure: always
